version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.23.2
    steps:
      - checkout
      - run: go mod download
      - run: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

